language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g codeclimate-test-reporter
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
    codeclimate-test-reporter < coverage/lcov.info
  fi
env:
  matrix:
  - TEST_TYPE=build
