language: node_js
node_js:
- '6'
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm install -g codeclimate-test-reporter
after_success:
- |
  if [ "$TEST_TYPE" = build ]; then
    codeclimate-test-reporter < coverage/lcov.info
  fi
env:
  matrix:
  - TEST_TYPE=build
  global:
    secure: LnRt6yeU2Flw4XvnjAar5CYm0xEp69JE+hz4odPX61XW19SgyiKHJ2sZfpxVVgP+m54hKrM3IZcxF61hF29ypV9+TUHKmMtofSlbo8SlqmiXBMuWK4jx/D/0EFay6nT54xpv8U2bfr0VjaBNBS4ZVXpptM5UWRxIIKK3bh/tdek=
